### ISSUE TITLE
Manga long description scrolling not working

### ISSUE THREAD

**Issue by j2ghz** [inorichi/mangafeed#13]
(details to be added) 
r291

**Comment by inorichi** [comment]
I was just doing that. Check it now. :)

**Comment by j2ghz** [comment]
Works better, but you can only scroll down, scrolling up trigger data refresh. I  would prefer the whole page to be scrolling, not just text inside description.

**Comment by inorichi** [comment]
Ok, is it good now?

**Comment by j2ghz** [comment]
Yes :+1:
