### ISSUE TITLE
Android 4.2.2 Issues

### ISSUE THREAD

**Issue by Syborg49** [inorichi/mangafeed#15]
https://imgur.com/a/vwzEk

IDK what's causing this. I'm assuming its a compatibility issue?

**Comment by inorichi** [comment]
Yes, it's. I've made a few changes to the theme. Everything should be displayed now.

The add to library button shouldn't be blue, but the info tab will probably be redesigned, so I will leave it like that.

**Comment by Syborg49** [comment]
Is the apk on the readme the updated one?

**Comment by inorichi** [comment]
Yes, it's auto updated.

**Comment by inorichi** [comment]
I've also fixed the button background. Close this issue if everything is fine.
