### ISSUE TITLE
Volume Covers

### ISSUE THREAD

**Issue by matayerbas** [inorichi/mangafeed#16]
Not sure if this qualifies as an issue, but I've noticed all catalogues minus batoto have low quality images for manga covers. Is this just batoto being the better source?

**Comment by inorichi** [comment]
I've set a better image decoder for covers. I don't think you will notice any difference though.

Images are downloaded at their original resolution. I guess the only solution is to increase the number of mangas per row (you can change it in the general section), but I have to update it to keep the aspect ratio (the height is always the same at the moment).

**Comment by matayerbas** [comment]
OK, thanks for the info. Good job with everything so far.

**Comment by matayerbas** [comment]
OK, thanks for the info. Good job with everything so far.
