### ISSUE TITLE
MAL selection differentiate manga and light novel

### ISSUE THREAD

**Issue by j2ghz** [inorichi/mangafeed#19]
Sometimes manga has exactly the same name as the light novel it's based on. In that case it's impossible to determine which is which since the interface shows just the name.

**Comment by inorichi** [comment]
I wanted to add the author (in case of similiar titles), but the API doesn't offer too much...

For example: http://myanimelist.net/api/manga/search.xml?q=itou-san (you may need to open the source code, MAL response is malformed :D)

There are two "Itou-san", I guess the only way is to show the cover.
