### ISSUE TITLE
Add option to set viewer for each individual manga.

### ISSUE THREAD

**Issue by marroma** [inorichi/mangafeed#21]
Title.

Having to go to through 4 menus is cumbersome. Can you add the option in the manga or chapter overview? I have a healthy mix of webtoons and manga and change the setting quite often.

**Comment by inorichi** [comment]
There's a menu inside the reader. Tap in the center and you will see an icon in the bottom to change the reader. It will change it only for that manga.

I guess the menu should be documented somehow.
