### ISSUE TITLE
3-dot dropdown on chapter list has black text on a black background.

### ISSUE THREAD

**Issue by wopian** [inorichi/mangafeed#24]
When opening the dropdown when long pressing chapters the text is black instead of the expected white text colour.

OS: CyanogenOS 12.1.1 (Lollipop 5.1.1)
App: r315

![](https://i.imgur.com/EZSmppJ.png)

**Comment by inorichi** [comment]
It was fixed on r319

**Comment by renzaluar** [comment]
If I am not mistaken, there can be shown 25 mangas HISTORY in the app at a time , after removing a manga , I can see the older manga started to show up among the 25. My question is, is it possible to show a lot more manga at a time in the history section without removing any?
Thanks for your hard work.
