### ISSUE TITLE
Release builds 

### ISSUE THREAD

**Issue by lc-guy** [inorichi/mangafeed#5]
Not everyone has access to an android development environment.

**Comment by Ligerx** [comment]
Didn't he say he wasn't ready to put out a release yet?
I think he said he didn't want to deal with too many feature requests and bugs until a basic functioning app was completed

**Comment by lc-guy** [comment]
My bad, ignore this in that case.

**Comment by inorichi** [comment]
Yes, please be patient. I don't think it will take too long for the first release.

**Comment by Ligerx** [comment]
Thanks for the update!
